export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const ADD_MESSAGE = "ADD_MESSAGE";
